---
# tasks file for moqaddas.myloadbalancer
- name: "Including Os Specific Variable"
  include_vars: "{{ ansible_os_family }}.yml"
- name: "Including the tasks for file for RHEL-8"
  include_tasks: "{{ ansible_os_family }}.yml"
